import = [
  "~/.config/alacritty/themes/themes/nord.toml"
]

[font]
normal = { family="JetBrainsMonoNL Nerd Font", style="Regular" }
bold = { family = "Hack", style = "Bold" }

[colors]
draw_bold_text_with_bright_colors = true

[keyboard]
bindings = [
   { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" }
]

